name: "Estimativa de custo Infracost"

on:
  pull_request:
    paths:
      - "**.tf"
  
jobs:
  infracost:
    uses: "EzzioMoreira/cicd_centralizado/.github/workflows/infracost.yaml@feat/add-infracost"
    secrets:
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

