name: "Estimativa de custo Infracost"

on:
  pull_request:

jobs:
  infracost:
    uses: "EzzioMoreira/rds-terraform/.github/workflows/infracost-master.yaml@master"
    secrets:
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
