name: "Estimativa de custo Infracost"

on: 
  pull_request:
  
jobs:
  terraform:
    uses: "EzzioMoreira/cicd_centralizado/.github/workflows/infracost.yaml@feat/add-infacost"
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
