name: Infracost exibe estimativa de custo da infraestrutura

on:
  workflow_call:
    inputs:
      os_version:
        description: "Versão do sistema operacional"
        required: false
        default: "ubuntu-20.04"
        type: string
      tf_directory:
        description: "Diretório do projeto terraform"
        required: false
        default: .
        type: string
    secrets:
      infracost_api_key:
        description: "APIKEY do Infracost"
        required: true
jobs:
  infracost:
    name: Infracost workflow
    runs-on: ${{ inputs.os_version }}
    if: github.event.pull_request
    env:
       INFRACOST_ENABLE_CLOUD: true
    steps:
      - name: Configura Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.infracost_api_key }}

      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Gerando estimativa de custo atual
        run: |
          infracost breakdown --path=${{ inputs.tf_directory }} \
                              --format=html \
                              --out-file=/tmp/infracost-base.html

      - name: Checkout PR branch
        uses: actions/checkout@v2

      - name: Gerando diferença de custo em relação à branch atual
        run: |
          infracost diff --path=${{ inputs.tf_directory }} \
                          --format=html \
                          --compare-to=/tmp/infracost-base.html \
                          --out-file=/tmp/infracost.html

      - name: Adicionando comentário no PR
        run: |
            cat /tmp/infracost.html >> $GITHUB_STEP_SUMMARY
            ls -lhs /tmp
            cat /tmp/infracost.html
